# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(default='http://pbs.twimg.com/profile_images/555400719478444032/ky9g4wh6.png'),
        ),
    ]
