# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
