# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='mugshot',
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='privacy',
            field=models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='closed', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy'),
        ),
    ]
