# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myprofile_favourite_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='favourite_pizza',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='mugshot',
        ),
    ]
