# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160819_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='favorite_RSS',
            field=models.CharField(default='http://www.http://singularityhub.com/feed/', max_length=5, verbose_name='Enter RSS feed URL'),
            preserve_default=False,
        ),
    ]
