# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myprofile_favorite_rss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='favorite_RSS',
            field=models.CharField(max_length=120, verbose_name='Enter RSS feed URL'),
        ),
    ]
